/*

 TILES_MEDIEVAL.H

 Include File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : None.
  Tile size            : 8 x 8
  Tiles                : 0 to 90

  Palette colors       : Included.
  SGB Palette          : None.
  CGB Palette          : Constant per entry.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/


/* Bank of tiles. */
#define TilesBank 0

/* Super Gameboy palette 0 */
#define TilesSGBPal0c0 6076
#define TilesSGBPal0c1 8935
#define TilesSGBPal0c2 6596
#define TilesSGBPal0c3 5344

/* Super Gameboy palette 1 */
#define TilesSGBPal1c0 6076
#define TilesSGBPal1c1 8935
#define TilesSGBPal1c2 6596
#define TilesSGBPal1c3 5344

/* Super Gameboy palette 2 */
#define TilesSGBPal2c0 6076
#define TilesSGBPal2c1 8935
#define TilesSGBPal2c2 6596
#define TilesSGBPal2c3 5344

/* Super Gameboy palette 3 */
#define TilesSGBPal3c0 6076
#define TilesSGBPal3c1 8935
#define TilesSGBPal3c2 6596
#define TilesSGBPal3c3 5344

/* Gameboy Color palette 0 */
#define TilesCGBPal0c0 4872
#define TilesCGBPal0c1 9100
#define TilesCGBPal0c2 32767
#define TilesCGBPal0c3 32767

/* Gameboy Color palette 1 */
#define TilesCGBPal1c0 23712
#define TilesCGBPal1c1 27008
#define TilesCGBPal1c2 29280
#define TilesCGBPal1c3 954

/* Gameboy Color palette 2 */
#define TilesCGBPal2c0 4872
#define TilesCGBPal2c1 31542
#define TilesCGBPal2c2 404
#define TilesCGBPal2c3 0

/* Gameboy Color palette 3 */
#define TilesCGBPal3c0 4872
#define TilesCGBPal3c1 31875
#define TilesCGBPal3c2 16513
#define TilesCGBPal3c3 3199

/* Gameboy Color palette 4 */
#define TilesCGBPal4c0 4872
#define TilesCGBPal4c1 9238
#define TilesCGBPal4c2 32713
#define TilesCGBPal4c3 6143

/* Gameboy Color palette 5 */
#define TilesCGBPal5c0 4872
#define TilesCGBPal5c1 8935
#define TilesCGBPal5c2 6596
#define TilesCGBPal5c3 5344

/* Gameboy Color palette 6 */
#define TilesCGBPal6c0 4872
#define TilesCGBPal6c1 506
#define TilesCGBPal6c2 1291
#define TilesCGBPal6c3 31511

/* Gameboy Color palette 7 */
#define TilesCGBPal7c0 4872
#define TilesCGBPal7c1 9100
#define TilesCGBPal7c2 0
#define TilesCGBPal7c3 148

/* CGB palette entries. */
#define TilesCGB0 0
#define TilesCGB1 1
#define TilesCGB2 1
#define TilesCGB3 1
#define TilesCGB4 1
#define TilesCGB5 1
#define TilesCGB6 6
#define TilesCGB7 6
#define TilesCGB8 6
#define TilesCGB9 6
#define TilesCGB10 7
#define TilesCGB11 7
#define TilesCGB12 7
#define TilesCGB13 7
#define TilesCGB14 7
#define TilesCGB15 7
#define TilesCGB16 7
#define TilesCGB17 7
#define TilesCGB18 7
#define TilesCGB19 7
#define TilesCGB20 7
#define TilesCGB21 7
#define TilesCGB22 7
#define TilesCGB23 7
#define TilesCGB24 7
#define TilesCGB25 7
#define TilesCGB26 7
#define TilesCGB27 7
#define TilesCGB28 7
#define TilesCGB29 7
#define TilesCGB30 7
#define TilesCGB31 7
#define TilesCGB32 7
#define TilesCGB33 7
#define TilesCGB34 7
#define TilesCGB35 7
#define TilesCGB36 7
#define TilesCGB37 7
#define TilesCGB38 7
#define TilesCGB39 7
#define TilesCGB40 7
#define TilesCGB41 7
#define TilesCGB42 7
#define TilesCGB43 7
#define TilesCGB44 7
#define TilesCGB45 7
#define TilesCGB46 4
#define TilesCGB47 4
#define TilesCGB48 0
#define TilesCGB49 0
#define TilesCGB50 3
#define TilesCGB51 3
#define TilesCGB52 3
#define TilesCGB53 0
#define TilesCGB54 0
#define TilesCGB55 0
#define TilesCGB56 0
#define TilesCGB57 0
#define TilesCGB58 0
#define TilesCGB59 0
#define TilesCGB60 4
#define TilesCGB61 4
#define TilesCGB62 4
#define TilesCGB63 4
#define TilesCGB64 4
#define TilesCGB65 0
#define TilesCGB66 0
#define TilesCGB67 0
#define TilesCGB68 0
#define TilesCGB69 0
#define TilesCGB70 2
#define TilesCGB71 2
#define TilesCGB72 2
#define TilesCGB73 2
#define TilesCGB74 6
#define TilesCGB75 6
#define TilesCGB76 0
#define TilesCGB77 0
#define TilesCGB78 0
#define TilesCGB79 0
#define TilesCGB80 0
#define TilesCGB81 0
#define TilesCGB82 0
#define TilesCGB83 0
#define TilesCGB84 0
#define TilesCGB85 0
#define TilesCGB86 0
#define TilesCGB87 0
#define TilesCGB88 0
#define TilesCGB89 0
#define TilesCGB90 0
/* Start of tile array. */
extern unsigned char Tiles[];

/* End of TILES_MEDIEVAL.H */
