/*

 TILES.H

 Include File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : None.
  Tile size            : 8 x 8
  Tiles                : 0 to 64

  Palette colors       : Included.
  SGB Palette          : None.
  CGB Palette          : Constant per entry.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/


/* Bank of tiles. */
#define TilesBank 0

/* Super Gameboy palette 0 */
#define TilesSGBPal0c0 6076
#define TilesSGBPal0c1 8935
#define TilesSGBPal0c2 6596
#define TilesSGBPal0c3 5344

/* Super Gameboy palette 1 */
#define TilesSGBPal1c0 6076
#define TilesSGBPal1c1 8935
#define TilesSGBPal1c2 6596
#define TilesSGBPal1c3 5344

/* Super Gameboy palette 2 */
#define TilesSGBPal2c0 6076
#define TilesSGBPal2c1 8935
#define TilesSGBPal2c2 6596
#define TilesSGBPal2c3 5344

/* Super Gameboy palette 3 */
#define TilesSGBPal3c0 6076
#define TilesSGBPal3c1 8935
#define TilesSGBPal3c2 6596
#define TilesSGBPal3c3 5344

/* Gameboy Color palette 0 */
#define TilesCGBPal0c0 0
#define TilesCGBPal0c1 32642
#define TilesCGBPal0c2 32063
#define TilesCGBPal0c3 32767

/* Gameboy Color palette 1 */
#define TilesCGBPal1c0 1088
#define TilesCGBPal1c1 127
#define TilesCGBPal1c2 3070
#define TilesCGBPal1c3 32456

/* Gameboy Color palette 2 */
#define TilesCGBPal2c0 2080
#define TilesCGBPal2c1 127
#define TilesCGBPal2c2 6142
#define TilesCGBPal2c3 992

/* Gameboy Color palette 3 */
#define TilesCGBPal3c0 1024
#define TilesCGBPal3c1 4095
#define TilesCGBPal3c2 639
#define TilesCGBPal3c3 31

/* Gameboy Color palette 4 */
#define TilesCGBPal4c0 0
#define TilesCGBPal4c1 32642
#define TilesCGBPal4c2 31
#define TilesCGBPal4c3 31865

/* Gameboy Color palette 5 */
#define TilesCGBPal5c0 9213
#define TilesCGBPal5c1 28895
#define TilesCGBPal5c2 14559
#define TilesCGBPal5c3 0

/* Gameboy Color palette 6 */
#define TilesCGBPal6c0 31943
#define TilesCGBPal6c1 8935
#define TilesCGBPal6c2 31870
#define TilesCGBPal6c3 32767

/* Gameboy Color palette 7 */
#define TilesCGBPal7c0 3263
#define TilesCGBPal7c1 8935
#define TilesCGBPal7c2 31741
#define TilesCGBPal7c3 10570

/* CGB palette entries. */
#define TilesCGB0 0
#define TilesCGB1 4
#define TilesCGB2 1
#define TilesCGB3 4
#define TilesCGB4 0
#define TilesCGB5 3
#define TilesCGB6 0
#define TilesCGB7 0
#define TilesCGB8 0
#define TilesCGB9 0
#define TilesCGB10 0
#define TilesCGB11 0
#define TilesCGB12 0
#define TilesCGB13 0
#define TilesCGB14 0
#define TilesCGB15 0
#define TilesCGB16 0
#define TilesCGB17 0
#define TilesCGB18 0
#define TilesCGB19 0
#define TilesCGB20 0
#define TilesCGB21 0
#define TilesCGB22 0
#define TilesCGB23 0
#define TilesCGB24 0
#define TilesCGB25 0
#define TilesCGB26 0
#define TilesCGB27 0
#define TilesCGB28 0
#define TilesCGB29 0
#define TilesCGB30 0
#define TilesCGB31 0
#define TilesCGB32 0
#define TilesCGB33 0
#define TilesCGB34 0
#define TilesCGB35 0
#define TilesCGB36 0
#define TilesCGB37 0
#define TilesCGB38 0
#define TilesCGB39 0
#define TilesCGB40 0
#define TilesCGB41 0
#define TilesCGB42 0
#define TilesCGB43 0
#define TilesCGB44 0
#define TilesCGB45 0
#define TilesCGB46 5
#define TilesCGB47 0
#define TilesCGB48 3
#define TilesCGB49 3
#define TilesCGB50 2
#define TilesCGB51 2
#define TilesCGB52 0
#define TilesCGB53 0
#define TilesCGB54 0
#define TilesCGB55 0
#define TilesCGB56 5
#define TilesCGB57 0
#define TilesCGB58 0
#define TilesCGB59 0
#define TilesCGB60 6
#define TilesCGB61 6
#define TilesCGB62 6
#define TilesCGB63 6
#define TilesCGB64 0
/* Start of tile array. */
extern unsigned char Tiles[];

/* End of TILES.H */
